name: build
on : push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copier code depuis Github vers notre Ubuntu
        uses: actions/checkout@v3
      - name: Installer nodeJS sur notre serveur Ubuntu
        uses: actions/setup-node@v3
      - name: installation des packages JS
        run: npm install
      - name: Build l'application JS
        run: npm run build
